# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Infoprog2020_config = debug

else ifeq ($(config),release)
  Infoprog2020_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Infoprog2020

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Infoprog2020:
ifneq (,$(Infoprog2020_config))
	@echo "==== Building Infoprog2020 ($(Infoprog2020_config)) ===="
	@${MAKE} --no-print-directory -C Infoprog2020 -f Makefile config=$(Infoprog2020_config)
endif

clean:
	@${MAKE} --no-print-directory -C Infoprog2020 -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Infoprog2020"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"